#!/usr/bin/python
import time
import argparse
import sys
from rhv4 import rhv4
from ConfigParser import SafeConfigParser



# Set debut Paramater
debug=0

# Start Main Loop here
try:
        parser = argparse.ArgumentParser(description="RHV Info Collection")
        parser.add_argument('-H', help='RHV host')
	parser.add_argument('-M', help='Move Flag')
        parser.add_argument('-d', help='debug')
        args = parser.parse_args()

        if(args.d) : debug = 1

        config = SafeConfigParser()
        config.filename="/usr/local/rhv/rhv.ini"
        config.read(config.filename)
        rhvm_instance = rhv4(config,debug)
	dataArr = rhvm_instance.migrateHost2defaultHost(args.H,args.M)
except Exception as ex:
        print "WARNING - General Exception : %s " % str(ex)
        sys.exit(1)

